// Package platformorchestratorapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package platformorchestratorapi

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	JwtAuthScopes      = "jwtAuth.Scopes"
	UserIdHeaderScopes = "userIdHeader.Scopes"
)

// Defines values for DeploymentCreateBodyMode.
const (
	Deploy   DeploymentCreateBodyMode = "deploy"
	PlanOnly DeploymentCreateBodyMode = "plan_only"
	Rollback DeploymentCreateBodyMode = "rollback"
)

// Defines values for DeploymentCreateBodyRunnerLogLevel.
const (
	DeploymentCreateBodyRunnerLogLevelDebug DeploymentCreateBodyRunnerLogLevel = "debug"
	DeploymentCreateBodyRunnerLogLevelError DeploymentCreateBodyRunnerLogLevel = "error"
	DeploymentCreateBodyRunnerLogLevelInfo  DeploymentCreateBodyRunnerLogLevel = "info"
	DeploymentCreateBodyRunnerLogLevelWarn  DeploymentCreateBodyRunnerLogLevel = "warn"
)

// Defines values for DeploymentDiffChangeType.
const (
	DeploymentDiffChangeTypeAdded         DeploymentDiffChangeType = "added"
	DeploymentDiffChangeTypeModuleChanged DeploymentDiffChangeType = "module_changed"
	DeploymentDiffChangeTypeParamsChanged DeploymentDiffChangeType = "params_changed"
	DeploymentDiffChangeTypeRemoved       DeploymentDiffChangeType = "removed"
)

// Defines values for DeploymentResultsUpdateBodyStatus.
const (
	Failure DeploymentResultsUpdateBodyStatus = "failure"
	Success DeploymentResultsUpdateBodyStatus = "success"
)

// Defines values for RemoteRunnerMessageAction.
const (
	CheckJobStatus RemoteRunnerMessageAction = "check-job-status"
	CreateJob      RemoteRunnerMessageAction = "create-job"
)

// ActiveResourceNode A node in the active resource graph
type ActiveResourceNode struct {
	DeploymentId openapi_types.UUID `json:"deployment_id"`
	Edges        map[string]string  `json:"edges"`

	// EnvId The environment id.
	EnvId string `json:"env_id"`

	// Id The deterministic hash of the node in the graph. This hash is also used in the edges map for each node.
	Id            string                 `json:"id"`
	Metadata      map[string]interface{} `json:"metadata"`
	ModuleId      string                 `json:"module_id"`
	ModuleVersion string                 `json:"module_version"`

	// ProjectId The Project id of the environment of this node.
	ProjectId     string `json:"project_id"`
	ResourceClass string `json:"resource_class"`
	ResourceId    string `json:"resource_id"`
	ResourceType  string `json:"resource_type"`
}

// Deployment defines model for Deployment.
type Deployment struct {
	// CompletedAt The time the deployment succeeded, failed, or terminated
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt The time the deployment was created
	CreatedAt time.Time `json:"created_at"`

	// CreatedBy The user that created the deployment
	CreatedBy openapi_types.UUID `json:"created_by"`

	// EnvId The Environment id in the project which is being deployed
	EnvId string `json:"env_id"`

	// Id The unique deployment id
	Id DeploymentId `json:"id"`

	// Manifest The manifest associated with a deployment
	Manifest DeploymentManifest `json:"manifest"`

	// Metrics Metrics resulting from a deployment.
	Metrics DeploymentMetrics `json:"metrics"`

	// Mode The mode of the deployment.
	Mode string `json:"mode"`

	// OrgId The Organization ID
	OrgId OrganizationId `json:"org_id"`

	// PlanOnly Whether the deployment is executed in plan mode.
	PlanOnly bool `json:"plan_only"`

	// ProjectId The Project id which the environment exists in
	ProjectId string `json:"project_id"`

	// RollbackToDeploymentId When mode is 'rollback', this field will hold the uuid of the deployment rollback to.
	RollbackToDeploymentId *openapi_types.UUID `json:"rollback_to_deployment_id,omitempty"`

	// RunnerId The Runner ID that this deployment executes on
	RunnerId string `json:"runner_id"`

	// Status The status of the deployment.
	Status string `json:"status"`

	// StatusMessage A message associated with the 'status'.
	StatusMessage string `json:"status_message"`
}

// DeploymentCreateBody defines model for DeploymentCreateBody.
type DeploymentCreateBody struct {
	// EncryptedLogsRecipient A recipient public key must be provided in order to encrypt the logs produced by the runner. This must be an 'age' public key (see https://age-encryption.org).
	// The caller must hold the matching private key in order to decrypt the logs when the logs url is provided. If the recipient key is not set, no logs will be captured
	// by the runner.
	EncryptedLogsRecipient *string `json:"encrypted_logs_recipient,omitempty"`

	// EncryptedOutputsRecipient A recipient public key must be provided in order to access encrypted outputs of the deployment. This must be an 'age' public key (see https://age-encryption.org).
	// The caller must hold the matching private key in order to decrypt the outputs when the deployment completes. If the recipient key is not set, no outputs will be captured
	// from the deployment.
	EncryptedOutputsRecipient *string `json:"encrypted_outputs_recipient,omitempty"`

	// EnvId The environment to deploy to.
	EnvId string `json:"env_id"`

	// IsDryRun Whether to just validate the request and not persist or execute it.
	IsDryRun bool `json:"is_dry_run,omitempty"`

	// Manifest The manifest associated with a deployment
	Manifest *DeploymentManifest `json:"manifest,omitempty"`

	// Mode The mode of the deployment. Defaults to 'deploy'. Can be set to 'rollback' to rollback to the graph used in
	// the deployment specified by `rollback_to_deployment_id`. For backwards compatibility, this can be set to
	// 'plan_only' which is equivalent to 'deploy' mode with plan_only set to true.
	Mode DeploymentCreateBodyMode `json:"mode"`

	// PlanOnly Whether the deployment should be planned only and not executed. This defaults to 'false' unless the mode is
	// set to 'plan_only'.
	PlanOnly *bool `json:"plan_only,omitempty"`

	// ProjectId The Project to deploy to.
	ProjectId string `json:"project_id"`

	// RollbackToDeploymentId Optional ID to rollback to when the deployment mode is 'rollback' or 'rollback_plan'.
	RollbackToDeploymentId *openapi_types.UUID `json:"rollback_to_deployment_id,omitempty"`

	// RunnerLogLevel The log level for the runner.
	RunnerLogLevel *DeploymentCreateBodyRunnerLogLevel `json:"runner_log_level,omitempty"`
}

// DeploymentCreateBodyMode The mode of the deployment. Defaults to 'deploy'. Can be set to 'rollback' to rollback to the graph used in
// the deployment specified by `rollback_to_deployment_id`. For backwards compatibility, this can be set to
// 'plan_only' which is equivalent to 'deploy' mode with plan_only set to true.
type DeploymentCreateBodyMode string

// DeploymentCreateBodyRunnerLogLevel The log level for the runner.
type DeploymentCreateBodyRunnerLogLevel string

// DeploymentDiff Describes a diff between the resource graphs of two deployments.
type DeploymentDiff struct {
	Changes []DeploymentDiffChange `json:"changes"`

	// FromDeploymentId The deployment ID the diff is calculated from. This will be null if there is no previous deployment.
	FromDeploymentId *openapi_types.UUID `json:"from_deployment_id,omitempty"`

	// NumAdded The number of resources added in the deployment.
	NumAdded int `json:"num_added"`

	// NumChanged The number of resources changed in the deployment.
	NumChanged int `json:"num_changed"`

	// NumRemoved The number of resources removed in the deployment.
	NumRemoved int `json:"num_removed"`

	// ToDeploymentId The deployment ID the diff is calculated to. This will be null if the diff is calculated from a dry-run.
	ToDeploymentId *openapi_types.UUID `json:"to_deployment_id,omitempty"`
}

// DeploymentDiffChange defines model for DeploymentDiffChange.
type DeploymentDiffChange struct {
	// Id The deterministic hash of the node.
	Id string `json:"id"`

	// Resource The resource identifier of the node including the type, class, and id
	Resource string `json:"resource"`

	// Summary A human readable summary of the change to this node.
	Summary string `json:"summary"`

	// Type The type of change in a resource node.
	Type DeploymentDiffChangeType `json:"type"`
}

// DeploymentDiffChangeType The type of change in a resource node.
type DeploymentDiffChangeType string

// DeploymentDryRun defines model for DeploymentDryRun.
type DeploymentDryRun struct {
	// Diff Describes a diff between the resource graphs of two deployments.
	Diff DeploymentDiff `json:"diff"`

	// RunnerId The Runner ID that this deployment would have executed on
	RunnerId string `json:"runner_id"`
}

// DeploymentEncryptedOutputs defines model for DeploymentEncryptedOutputs.
type DeploymentEncryptedOutputs struct {
	// Raw The base64 encoded encrypted outputs. These are returned in standard base64 with padding. The outputs are encrypted with https://age-encryption.org/ and may
	// be decrypted by the holder of the recipients key.
	Raw string `json:"raw"`
}

// DeploymentId The unique deployment id
type DeploymentId = openapi_types.UUID

// DeploymentManifest The manifest associated with a deployment
type DeploymentManifest struct {
	// Shared The set of named shared resources.
	Shared map[string]DeploymentManifestResource `json:"shared,omitempty"`

	// Workloads The set of workloads in the environment.
	Workloads map[string]DeploymentManifestWorkload `json:"workloads"`
}

// DeploymentManifestResource A resource to provision as part of the deployment
type DeploymentManifestResource struct {
	// Class A resource class requested by the resource graph. 'default' is the default value.
	Class *ResourceClass `json:"class,omitempty"`

	// Id A specific resource id requested by the resource graph
	Id *ResourceId `json:"id,omitempty"`

	// Params Optional parameters to pass to the resource provisioning.
	Params map[string]interface{} `json:"params,omitempty"`

	// Type The resource type to provision
	Type string `json:"type"`
}

// DeploymentManifestWorkload defines model for DeploymentManifestWorkload.
type DeploymentManifestWorkload struct {
	Outputs   map[string]string                     `json:"outputs,omitempty"`
	Resources map[string]DeploymentManifestResource `json:"resources,omitempty"`

	// Variables Parameter variables is deprecated and will be removed in a future release. Please use outputs instead.
	// Deprecated:
	Variables map[string]string `json:"variables,omitempty" yaml:"variables,omitempty"`
}

// DeploymentMetrics Metrics resulting from a deployment.
type DeploymentMetrics struct {
	// NumResourceNodes The number of resource nodes in the graph.
	NumResourceNodes int `json:"num_resource_nodes"`

	// NumTfResources The number of terraformed resources. Only known after deployment.
	NumTfResources *int `json:"num_tf_resources,omitempty"`

	// NumTfResourcesAdded The number of terraformed resources added. Only known after deployment.
	NumTfResourcesAdded *int `json:"num_tf_resources_added,omitempty"`

	// NumTfResourcesChanged The number of terraformed resources changed. Only known after deployment.
	NumTfResourcesChanged *int `json:"num_tf_resources_changed,omitempty"`

	// NumTfResourcesRemoved The number of terraformed resources removed. Only known after deployment.
	NumTfResourcesRemoved *int `json:"num_tf_resources_removed,omitempty"`

	// NumWorkloads The number of workloads in the deployment.
	NumWorkloads int `json:"num_workloads"`
}

// DeploymentResultMetadata The metadata produced by the resources involved in the deployment.
type DeploymentResultMetadata = []DeploymentResultMetadataPerNode

// DeploymentResultMetadataPerNode The metadata produced by a specific resource identified by its hash.
type DeploymentResultMetadataPerNode struct {
	// Metadata The metadata output by the module which provisioned the resource.
	Metadata map[string]interface{} `json:"metadata"`

	// NodeId The hash of the active resource node.
	NodeId string `json:"node_id"`
}

// DeploymentResultsUpdateBody The outcome of the runner execution.
type DeploymentResultsUpdateBody struct {
	// Error A standard error response
	Error *Error `json:"error,omitempty"`

	// Metadata The metadata produced by the resources involved in the deployment.
	Metadata DeploymentResultMetadata `json:"metadata,omitempty"`

	// Outputs The encrypted outputs produced by the runner.
	Outputs *string `json:"outputs,omitempty"`

	// Status The overall status of the runner execution.
	Status DeploymentResultsUpdateBodyStatus `json:"status"`

	// TfResourceCounts Details about the Terraform resources added / removed / changed .
	TfResourceCounts DeploymentTFResourceCounts `json:"tf_resource_counts,omitempty"`
}

// DeploymentResultsUpdateBodyStatus The overall status of the runner execution.
type DeploymentResultsUpdateBodyStatus string

// DeploymentSummary Summary information for a deployment, more information can be retrieved through the GetDeployment APIs.
type DeploymentSummary struct {
	// CompletedAt The time the deployment succeeded, failed, or terminated
	CompletedAt *time.Time `json:"completed_at,omitempty"`

	// CreatedAt The time the deployment was created
	CreatedAt time.Time `json:"created_at"`

	// CreatedBy The user that created the deployment
	CreatedBy openapi_types.UUID `json:"created_by"`

	// EnvId The Environment id in the project which is being deployed
	EnvId string `json:"env_id"`

	// Id The unique deployment id
	Id DeploymentId `json:"id"`

	// Metrics Metrics resulting from a deployment.
	Metrics DeploymentMetrics `json:"metrics"`

	// Mode The mode of the deployment.
	Mode string `json:"mode"`

	// OrgId The Organization ID
	OrgId OrganizationId `json:"org_id"`

	// PlanOnly Whether the deployment is executed in plan mode.
	PlanOnly bool `json:"plan_only"`

	// ProjectId The Project id which the environment exists in
	ProjectId string `json:"project_id"`

	// RollbackToDeploymentId When mode is 'rollback', this field will hold the uuid of the deployment rollback to.
	RollbackToDeploymentId *openapi_types.UUID `json:"rollback_to_deployment_id,omitempty"`

	// Status The status of the deployment.
	Status string `json:"status"`

	// StatusMessage A message associated with the 'status'.
	StatusMessage string `json:"status_message"`
}

// DeploymentTFResourceCounts Details about the Terraform resources added / removed / changed .
type DeploymentTFResourceCounts struct {
	// NumResources Number of Terraform resources involved in the deployment.
	NumResources int `json:"num_resources"`

	// NumResourcesAdded Number of Terraform resources added by this deployment run.
	NumResourcesAdded int `json:"num_resources_added"`

	// NumResourcesChanged Number of Terraform resources changed by this deployment run.
	NumResourcesChanged int `json:"num_resources_changed"`

	// NumResourcesRemoved Number of Terraform resources removed by this deployment run.
	NumResourcesRemoved int `json:"num_resources_removed"`
}

// Error A standard error response
type Error struct {
	// Details An optional payload of metadata associated with the error.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error A short code representing the class of error. This code can be used for tracking and observability or to
	// find appropriate troubleshooting documentation.
	Error string `json:"error"`

	// Message A human-readable explanation of the error.
	Message string `json:"message"`
}

// ListActiveResourceNodesPage defines model for ListActiveResourceNodesPage.
type ListActiveResourceNodesPage struct {
	// Items The list of active resource nodes.
	Items []ActiveResourceNode `json:"items"`
}

// OrganizationId The Organization ID
type OrganizationId = string

// RemoteRunnerMessage defines model for RemoteRunnerMessage.
type RemoteRunnerMessage struct {
	union json.RawMessage
}

// RemoteRunnerMessageAction The action to be performed by the remote runner.
type RemoteRunnerMessageAction string

// RemoteRunnerMessageCheckJobStatus The response for checking the status of a job on the runner.
type RemoteRunnerMessageCheckJobStatus struct {
	// Action The action to be performed by the remote runner.
	Action RemoteRunnerMessageAction `json:"action"`

	// DeploymentToken The deployment token to authenticate any request to update deployment results from the remote runner.
	DeploymentToken string `json:"deployment_token"`

	// ExpiresAt The time at which the job should be considered stuck by the runner if no pods are running or completed.
	ExpiresAt time.Time `json:"expires_at"`

	// JobId The ID of the job whose status is being requested.
	JobId string `json:"job_id"`

	// Namespace The ID of the namespace associated with the job.
	Namespace string `json:"namespace"`
}

// RemoteRunnerMessageCreateJob The response for creating a job on the runner.
type RemoteRunnerMessageCreateJob struct {
	// Action The action to be performed by the remote runner.
	Action RemoteRunnerMessageAction `json:"action"`

	// Configuration The configuration for the job to be created on the runner. It must be parsable into a kubernetes Job definition.
	Configuration map[string]interface{} `json:"configuration"`

	// DeploymentToken The deployment token to authenticate any request to update deployment results from the remote runner.
	DeploymentToken string `json:"deployment_token"`

	// JobId The ID of the job created on the runner.
	JobId string `json:"job_id"`

	// Namespace The ID of the namespace associated with the job.
	Namespace string `json:"namespace"`
}

// ResourceClass A resource class requested by the resource graph. 'default' is the default value.
type ResourceClass = string

// ResourceId A specific resource id requested by the resource graph
type ResourceId = string

// DeploymentIdPathParam defines model for deploymentIdPathParam.
type DeploymentIdPathParam = openapi_types.UUID

// EnvIdQueryParam defines model for envIdQueryParam.
type EnvIdQueryParam = string

// OrgIdPathParam defines model for orgIdPathParam.
type OrgIdPathParam = string

// ProjectIdQueryParam defines model for projectIdQueryParam.
type ProjectIdQueryParam = string

// RunnerIdPathParam defines model for runnerIdPathParam.
type RunnerIdPathParam = string

// N400BadRequest A standard error response
type N400BadRequest = Error

// N404NotFound A standard error response
type N404NotFound = Error

// N409Conflict A standard error response
type N409Conflict = Error

// ListActiveResourceNodesParams defines parameters for ListActiveResourceNodes.
type ListActiveResourceNodesParams struct {
	// ProjectId The Project ID
	ProjectId *ProjectIdQueryParam `form:"project_id,omitempty" json:"project_id,omitempty"`

	// EnvId The Environment ID
	EnvId *EnvIdQueryParam `form:"env_id,omitempty" json:"env_id,omitempty"`
}

// CreateDeploymentParams defines parameters for CreateDeployment.
type CreateDeploymentParams struct {
	// IdempotencyKey Ensures that the deployment request is only accepted once per idempotency key per 24 hours. A uuid or similar is recommended.
	// When the key matches the key in last deployment and the environment and manifest is the same, this will return the last deployment.
	IdempotencyKey *string `json:"Idempotency-Key,omitempty"`
}

// GetDeploymentLogsParams defines parameters for GetDeploymentLogs.
type GetDeploymentLogsParams struct {
	// DecryptKey The private key needed to decrypt the logs. It should be an 'age' private key (see https://age-encryption.org).
	DecryptKey *string `json:"DecryptKey,omitempty"`
}

// WaitForDeploymentCompleteParams defines parameters for WaitForDeploymentComplete.
type WaitForDeploymentCompleteParams struct {
	// TimeoutInSeconds Sets a maximum timeout before the HTTP-408 response is returned.
	TimeoutInSeconds *int `form:"timeout_in_seconds,omitempty" json:"timeout_in_seconds,omitempty"`
}

// GetDeploymentBundleParams defines parameters for GetDeploymentBundle.
type GetDeploymentBundleParams struct {
	XDeploymentToken string `json:"X-Deployment-Token"`
}

// UpdateDeploymentResultsParams defines parameters for UpdateDeploymentResults.
type UpdateDeploymentResultsParams struct {
	XDeploymentToken string `json:"X-Deployment-Token"`
}

// CreateDeploymentJSONRequestBody defines body for CreateDeployment for application/json ContentType.
type CreateDeploymentJSONRequestBody = DeploymentCreateBody

// UpdateDeploymentResultsJSONRequestBody defines body for UpdateDeploymentResults for application/json ContentType.
type UpdateDeploymentResultsJSONRequestBody = DeploymentResultsUpdateBody

// AsRemoteRunnerMessageCreateJob returns the union data inside the RemoteRunnerMessage as a RemoteRunnerMessageCreateJob
func (t RemoteRunnerMessage) AsRemoteRunnerMessageCreateJob() (RemoteRunnerMessageCreateJob, error) {
	var body RemoteRunnerMessageCreateJob
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRemoteRunnerMessageCreateJob overwrites any union data inside the RemoteRunnerMessage as the provided RemoteRunnerMessageCreateJob
func (t *RemoteRunnerMessage) FromRemoteRunnerMessageCreateJob(v RemoteRunnerMessageCreateJob) error {
	v.Action = "create-job"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRemoteRunnerMessageCreateJob performs a merge with any union data inside the RemoteRunnerMessage, using the provided RemoteRunnerMessageCreateJob
func (t *RemoteRunnerMessage) MergeRemoteRunnerMessageCreateJob(v RemoteRunnerMessageCreateJob) error {
	v.Action = "create-job"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsRemoteRunnerMessageCheckJobStatus returns the union data inside the RemoteRunnerMessage as a RemoteRunnerMessageCheckJobStatus
func (t RemoteRunnerMessage) AsRemoteRunnerMessageCheckJobStatus() (RemoteRunnerMessageCheckJobStatus, error) {
	var body RemoteRunnerMessageCheckJobStatus
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromRemoteRunnerMessageCheckJobStatus overwrites any union data inside the RemoteRunnerMessage as the provided RemoteRunnerMessageCheckJobStatus
func (t *RemoteRunnerMessage) FromRemoteRunnerMessageCheckJobStatus(v RemoteRunnerMessageCheckJobStatus) error {
	v.Action = "check-job-status"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeRemoteRunnerMessageCheckJobStatus performs a merge with any union data inside the RemoteRunnerMessage, using the provided RemoteRunnerMessageCheckJobStatus
func (t *RemoteRunnerMessage) MergeRemoteRunnerMessageCheckJobStatus(v RemoteRunnerMessageCheckJobStatus) error {
	v.Action = "check-job-status"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RemoteRunnerMessage) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"action"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t RemoteRunnerMessage) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "check-job-status":
		return t.AsRemoteRunnerMessageCheckJobStatus()
	case "create-job":
		return t.AsRemoteRunnerMessageCreateJob()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t RemoteRunnerMessage) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RemoteRunnerMessage) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// ListActiveResourceNodes request
	ListActiveResourceNodes(ctx context.Context, orgId OrgIdPathParam, params *ListActiveResourceNodesParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateDeploymentWithBody request with any body
	CreateDeploymentWithBody(ctx context.Context, orgId OrgIdPathParam, params *CreateDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateDeployment(ctx context.Context, orgId OrgIdPathParam, params *CreateDeploymentParams, body CreateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeployment request
	GetDeployment(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeploymentLogs request
	GetDeploymentLogs(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WaitForDeploymentComplete request
	WaitForDeploymentComplete(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *WaitForDeploymentCompleteParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeploymentBundle request
	GetDeploymentBundle(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentBundleParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetDeploymentEncryptedOutputs request
	GetDeploymentEncryptedOutputs(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error)

	// UpdateDeploymentResultsWithBody request with any body
	UpdateDeploymentResultsWithBody(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	UpdateDeploymentResults(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, body UpdateDeploymentResultsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// WaitForRemoteRunnerMessages request
	WaitForRemoteRunnerMessages(ctx context.Context, orgId OrgIdPathParam, runnerId RunnerIdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) ListActiveResourceNodes(ctx context.Context, orgId OrgIdPathParam, params *ListActiveResourceNodesParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListActiveResourceNodesRequest(c.Server, orgId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDeploymentWithBody(ctx context.Context, orgId OrgIdPathParam, params *CreateDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDeploymentRequestWithBody(c.Server, orgId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateDeployment(ctx context.Context, orgId OrgIdPathParam, params *CreateDeploymentParams, body CreateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateDeploymentRequest(c.Server, orgId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeployment(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeploymentRequest(c.Server, orgId, deploymentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeploymentLogs(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentLogsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeploymentLogsRequest(c.Server, orgId, deploymentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WaitForDeploymentComplete(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *WaitForDeploymentCompleteParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWaitForDeploymentCompleteRequest(c.Server, orgId, deploymentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeploymentBundle(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentBundleParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeploymentBundleRequest(c.Server, orgId, deploymentId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetDeploymentEncryptedOutputs(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetDeploymentEncryptedOutputsRequest(c.Server, orgId, deploymentId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDeploymentResultsWithBody(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDeploymentResultsRequestWithBody(c.Server, orgId, deploymentId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) UpdateDeploymentResults(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, body UpdateDeploymentResultsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewUpdateDeploymentResultsRequest(c.Server, orgId, deploymentId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) WaitForRemoteRunnerMessages(ctx context.Context, orgId OrgIdPathParam, runnerId RunnerIdPathParam, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewWaitForRemoteRunnerMessagesRequest(c.Server, orgId, runnerId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListActiveResourceNodesRequest generates requests for ListActiveResourceNodes
func NewListActiveResourceNodesRequest(server string, orgId OrgIdPathParam, params *ListActiveResourceNodesParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/active-resources", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ProjectId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "project_id", runtime.ParamLocationQuery, *params.ProjectId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.EnvId != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "env_id", runtime.ParamLocationQuery, *params.EnvId); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateDeploymentRequest calls the generic CreateDeployment builder with application/json body
func NewCreateDeploymentRequest(server string, orgId OrgIdPathParam, params *CreateDeploymentParams, body CreateDeploymentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateDeploymentRequestWithBody(server, orgId, params, "application/json", bodyReader)
}

// NewCreateDeploymentRequestWithBody generates requests for CreateDeployment with any type of body
func NewCreateDeploymentRequestWithBody(server string, orgId OrgIdPathParam, params *CreateDeploymentParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/deployments", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.IdempotencyKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "Idempotency-Key", runtime.ParamLocationHeader, *params.IdempotencyKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("Idempotency-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetDeploymentRequest generates requests for GetDeployment
func NewGetDeploymentRequest(server string, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deploymentId", runtime.ParamLocationPath, deploymentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/deployments/%s", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeploymentLogsRequest generates requests for GetDeploymentLogs
func NewGetDeploymentLogsRequest(server string, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentLogsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deploymentId", runtime.ParamLocationPath, deploymentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/deployments/%s/actions/get-logs", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.DecryptKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "DecryptKey", runtime.ParamLocationHeader, *params.DecryptKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("DecryptKey", headerParam0)
		}

	}

	return req, nil
}

// NewWaitForDeploymentCompleteRequest generates requests for WaitForDeploymentComplete
func NewWaitForDeploymentCompleteRequest(server string, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *WaitForDeploymentCompleteParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deploymentId", runtime.ParamLocationPath, deploymentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/deployments/%s/actions/wait-for-complete", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.TimeoutInSeconds != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "timeout_in_seconds", runtime.ParamLocationQuery, *params.TimeoutInSeconds); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetDeploymentBundleRequest generates requests for GetDeploymentBundle
func NewGetDeploymentBundleRequest(server string, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentBundleParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deploymentId", runtime.ParamLocationPath, deploymentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/deployments/%s/bundle", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Deployment-Token", runtime.ParamLocationHeader, params.XDeploymentToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Deployment-Token", headerParam0)

	}

	return req, nil
}

// NewGetDeploymentEncryptedOutputsRequest generates requests for GetDeploymentEncryptedOutputs
func NewGetDeploymentEncryptedOutputsRequest(server string, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deploymentId", runtime.ParamLocationPath, deploymentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/deployments/%s/encrypted-outputs", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewUpdateDeploymentResultsRequest calls the generic UpdateDeploymentResults builder with application/json body
func NewUpdateDeploymentResultsRequest(server string, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, body UpdateDeploymentResultsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewUpdateDeploymentResultsRequestWithBody(server, orgId, deploymentId, params, "application/json", bodyReader)
}

// NewUpdateDeploymentResultsRequestWithBody generates requests for UpdateDeploymentResults with any type of body
func NewUpdateDeploymentResultsRequestWithBody(server string, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "deploymentId", runtime.ParamLocationPath, deploymentId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/deployments/%s/results", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Deployment-Token", runtime.ParamLocationHeader, params.XDeploymentToken)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Deployment-Token", headerParam0)

	}

	return req, nil
}

// NewWaitForRemoteRunnerMessagesRequest generates requests for WaitForRemoteRunnerMessages
func NewWaitForRemoteRunnerMessagesRequest(server string, orgId OrgIdPathParam, runnerId RunnerIdPathParam) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "orgId", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithLocation("simple", false, "runnerId", runtime.ParamLocationPath, runnerId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/remote-runners/%s/actions/poll-requests", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// ListActiveResourceNodesWithResponse request
	ListActiveResourceNodesWithResponse(ctx context.Context, orgId OrgIdPathParam, params *ListActiveResourceNodesParams, reqEditors ...RequestEditorFn) (*ListActiveResourceNodesResponse, error)

	// CreateDeploymentWithBodyWithResponse request with any body
	CreateDeploymentWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, params *CreateDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDeploymentResponse, error)

	CreateDeploymentWithResponse(ctx context.Context, orgId OrgIdPathParam, params *CreateDeploymentParams, body CreateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDeploymentResponse, error)

	// GetDeploymentWithResponse request
	GetDeploymentWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, reqEditors ...RequestEditorFn) (*GetDeploymentResponse, error)

	// GetDeploymentLogsWithResponse request
	GetDeploymentLogsWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentLogsParams, reqEditors ...RequestEditorFn) (*GetDeploymentLogsResponse, error)

	// WaitForDeploymentCompleteWithResponse request
	WaitForDeploymentCompleteWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *WaitForDeploymentCompleteParams, reqEditors ...RequestEditorFn) (*WaitForDeploymentCompleteResponse, error)

	// GetDeploymentBundleWithResponse request
	GetDeploymentBundleWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentBundleParams, reqEditors ...RequestEditorFn) (*GetDeploymentBundleResponse, error)

	// GetDeploymentEncryptedOutputsWithResponse request
	GetDeploymentEncryptedOutputsWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, reqEditors ...RequestEditorFn) (*GetDeploymentEncryptedOutputsResponse, error)

	// UpdateDeploymentResultsWithBodyWithResponse request with any body
	UpdateDeploymentResultsWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDeploymentResultsResponse, error)

	UpdateDeploymentResultsWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, body UpdateDeploymentResultsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDeploymentResultsResponse, error)

	// WaitForRemoteRunnerMessagesWithResponse request
	WaitForRemoteRunnerMessagesWithResponse(ctx context.Context, orgId OrgIdPathParam, runnerId RunnerIdPathParam, reqEditors ...RequestEditorFn) (*WaitForRemoteRunnerMessagesResponse, error)
}

type ListActiveResourceNodesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListActiveResourceNodesPage
	JSON400      *N400BadRequest
	JSON404      *N404NotFound
}

// Status returns HTTPResponse.Status
func (r ListActiveResourceNodesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListActiveResourceNodesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateDeploymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeploymentDryRun
	JSON201      *Deployment
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateDeploymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateDeploymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDeploymentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Deployment
	JSON404      *N404NotFound
}

// Status returns HTTPResponse.Status
func (r GetDeploymentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeploymentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDeploymentLogsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *N400BadRequest
	JSON404      *N404NotFound
}

// Status returns HTTPResponse.Status
func (r GetDeploymentLogsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeploymentLogsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WaitForDeploymentCompleteResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Deployment
	JSON404      *N404NotFound
	JSON408      *Error
}

// Status returns HTTPResponse.Status
func (r WaitForDeploymentCompleteResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WaitForDeploymentCompleteResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDeploymentBundleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *N400BadRequest
	JSON404      *N404NotFound
}

// Status returns HTTPResponse.Status
func (r GetDeploymentBundleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeploymentBundleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetDeploymentEncryptedOutputsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *DeploymentEncryptedOutputs
	JSON404      *N404NotFound
}

// Status returns HTTPResponse.Status
func (r GetDeploymentEncryptedOutputsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetDeploymentEncryptedOutputsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type UpdateDeploymentResultsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON400      *N400BadRequest
	JSON404      *N404NotFound
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r UpdateDeploymentResultsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r UpdateDeploymentResultsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type WaitForRemoteRunnerMessagesResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *RemoteRunnerMessage
	JSON404      *N404NotFound
}

// Status returns HTTPResponse.Status
func (r WaitForRemoteRunnerMessagesResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r WaitForRemoteRunnerMessagesResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ListActiveResourceNodesWithResponse request returning *ListActiveResourceNodesResponse
func (c *ClientWithResponses) ListActiveResourceNodesWithResponse(ctx context.Context, orgId OrgIdPathParam, params *ListActiveResourceNodesParams, reqEditors ...RequestEditorFn) (*ListActiveResourceNodesResponse, error) {
	rsp, err := c.ListActiveResourceNodes(ctx, orgId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListActiveResourceNodesResponse(rsp)
}

// CreateDeploymentWithBodyWithResponse request with arbitrary body returning *CreateDeploymentResponse
func (c *ClientWithResponses) CreateDeploymentWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, params *CreateDeploymentParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateDeploymentResponse, error) {
	rsp, err := c.CreateDeploymentWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDeploymentResponse(rsp)
}

func (c *ClientWithResponses) CreateDeploymentWithResponse(ctx context.Context, orgId OrgIdPathParam, params *CreateDeploymentParams, body CreateDeploymentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateDeploymentResponse, error) {
	rsp, err := c.CreateDeployment(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateDeploymentResponse(rsp)
}

// GetDeploymentWithResponse request returning *GetDeploymentResponse
func (c *ClientWithResponses) GetDeploymentWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, reqEditors ...RequestEditorFn) (*GetDeploymentResponse, error) {
	rsp, err := c.GetDeployment(ctx, orgId, deploymentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeploymentResponse(rsp)
}

// GetDeploymentLogsWithResponse request returning *GetDeploymentLogsResponse
func (c *ClientWithResponses) GetDeploymentLogsWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentLogsParams, reqEditors ...RequestEditorFn) (*GetDeploymentLogsResponse, error) {
	rsp, err := c.GetDeploymentLogs(ctx, orgId, deploymentId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeploymentLogsResponse(rsp)
}

// WaitForDeploymentCompleteWithResponse request returning *WaitForDeploymentCompleteResponse
func (c *ClientWithResponses) WaitForDeploymentCompleteWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *WaitForDeploymentCompleteParams, reqEditors ...RequestEditorFn) (*WaitForDeploymentCompleteResponse, error) {
	rsp, err := c.WaitForDeploymentComplete(ctx, orgId, deploymentId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWaitForDeploymentCompleteResponse(rsp)
}

// GetDeploymentBundleWithResponse request returning *GetDeploymentBundleResponse
func (c *ClientWithResponses) GetDeploymentBundleWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *GetDeploymentBundleParams, reqEditors ...RequestEditorFn) (*GetDeploymentBundleResponse, error) {
	rsp, err := c.GetDeploymentBundle(ctx, orgId, deploymentId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeploymentBundleResponse(rsp)
}

// GetDeploymentEncryptedOutputsWithResponse request returning *GetDeploymentEncryptedOutputsResponse
func (c *ClientWithResponses) GetDeploymentEncryptedOutputsWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, reqEditors ...RequestEditorFn) (*GetDeploymentEncryptedOutputsResponse, error) {
	rsp, err := c.GetDeploymentEncryptedOutputs(ctx, orgId, deploymentId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetDeploymentEncryptedOutputsResponse(rsp)
}

// UpdateDeploymentResultsWithBodyWithResponse request with arbitrary body returning *UpdateDeploymentResultsResponse
func (c *ClientWithResponses) UpdateDeploymentResultsWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*UpdateDeploymentResultsResponse, error) {
	rsp, err := c.UpdateDeploymentResultsWithBody(ctx, orgId, deploymentId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDeploymentResultsResponse(rsp)
}

func (c *ClientWithResponses) UpdateDeploymentResultsWithResponse(ctx context.Context, orgId OrgIdPathParam, deploymentId DeploymentIdPathParam, params *UpdateDeploymentResultsParams, body UpdateDeploymentResultsJSONRequestBody, reqEditors ...RequestEditorFn) (*UpdateDeploymentResultsResponse, error) {
	rsp, err := c.UpdateDeploymentResults(ctx, orgId, deploymentId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseUpdateDeploymentResultsResponse(rsp)
}

// WaitForRemoteRunnerMessagesWithResponse request returning *WaitForRemoteRunnerMessagesResponse
func (c *ClientWithResponses) WaitForRemoteRunnerMessagesWithResponse(ctx context.Context, orgId OrgIdPathParam, runnerId RunnerIdPathParam, reqEditors ...RequestEditorFn) (*WaitForRemoteRunnerMessagesResponse, error) {
	rsp, err := c.WaitForRemoteRunnerMessages(ctx, orgId, runnerId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseWaitForRemoteRunnerMessagesResponse(rsp)
}

// ParseListActiveResourceNodesResponse parses an HTTP response from a ListActiveResourceNodesWithResponse call
func ParseListActiveResourceNodesResponse(rsp *http.Response) (*ListActiveResourceNodesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListActiveResourceNodesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListActiveResourceNodesPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseCreateDeploymentResponse parses an HTTP response from a CreateDeploymentWithResponse call
func ParseCreateDeploymentResponse(rsp *http.Response) (*CreateDeploymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateDeploymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeploymentDryRun
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseGetDeploymentResponse parses an HTTP response from a GetDeploymentWithResponse call
func ParseGetDeploymentResponse(rsp *http.Response) (*GetDeploymentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeploymentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetDeploymentLogsResponse parses an HTTP response from a GetDeploymentLogsWithResponse call
func ParseGetDeploymentLogsResponse(rsp *http.Response) (*GetDeploymentLogsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeploymentLogsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseWaitForDeploymentCompleteResponse parses an HTTP response from a WaitForDeploymentCompleteWithResponse call
func ParseWaitForDeploymentCompleteResponse(rsp *http.Response) (*WaitForDeploymentCompleteResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WaitForDeploymentCompleteResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Deployment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 408:
		var dest Error
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON408 = &dest

	}

	return response, nil
}

// ParseGetDeploymentBundleResponse parses an HTTP response from a GetDeploymentBundleWithResponse call
func ParseGetDeploymentBundleResponse(rsp *http.Response) (*GetDeploymentBundleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeploymentBundleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseGetDeploymentEncryptedOutputsResponse parses an HTTP response from a GetDeploymentEncryptedOutputsWithResponse call
func ParseGetDeploymentEncryptedOutputsResponse(rsp *http.Response) (*GetDeploymentEncryptedOutputsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetDeploymentEncryptedOutputsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest DeploymentEncryptedOutputs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}

// ParseUpdateDeploymentResultsResponse parses an HTTP response from a UpdateDeploymentResultsWithResponse call
func ParseUpdateDeploymentResultsResponse(rsp *http.Response) (*UpdateDeploymentResultsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &UpdateDeploymentResultsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseWaitForRemoteRunnerMessagesResponse parses an HTTP response from a WaitForRemoteRunnerMessagesWithResponse call
func ParseWaitForRemoteRunnerMessagesResponse(rsp *http.Response) (*WaitForRemoteRunnerMessagesResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &WaitForRemoteRunnerMessagesResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest RemoteRunnerMessage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404NotFound
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON404 = &dest

	}

	return response, nil
}
