// Package platformorchestratorcp provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package platformorchestratorcp

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	UserIdHeaderScopes = "userIdHeader.Scopes"
)

// Defines values for EnvironmentStatus.
const (
	EnvironmentStatusActive       EnvironmentStatus = "active"
	EnvironmentStatusDeleteFailed EnvironmentStatus = "delete_failed"
	EnvironmentStatusDeleting     EnvironmentStatus = "deleting"
)

// Valid indicates whether the value is a known member of the EnvironmentStatus enum.
func (e EnvironmentStatus) Valid() bool {
	switch e {
	case EnvironmentStatusActive:
		return true
	case EnvironmentStatusDeleteFailed:
		return true
	case EnvironmentStatusDeleting:
		return true
	default:
		return false
	}
}

// Defines values for OrganizationSource.
const (
	Internal OrganizationSource = "internal"
	Public   OrganizationSource = "public"
)

// Valid indicates whether the value is a known member of the OrganizationSource enum.
func (e OrganizationSource) Valid() bool {
	switch e {
	case Internal:
		return true
	case Public:
		return true
	default:
		return false
	}
}

// Defines values for ProjectStatus.
const (
	ProjectStatusActive   ProjectStatus = "active"
	ProjectStatusDeleting ProjectStatus = "deleting"
)

// Valid indicates whether the value is a known member of the ProjectStatus enum.
func (e ProjectStatus) Valid() bool {
	switch e {
	case ProjectStatusActive:
		return true
	case ProjectStatusDeleting:
		return true
	default:
		return false
	}
}

// Defines values for RunnerType.
const (
	RunnerTypeKubernetes      RunnerType = "kubernetes"
	RunnerTypeKubernetesAgent RunnerType = "kubernetes-agent"
	RunnerTypeKubernetesGke   RunnerType = "kubernetes-gke"
)

// Valid indicates whether the value is a known member of the RunnerType enum.
func (e RunnerType) Valid() bool {
	switch e {
	case RunnerTypeKubernetes:
		return true
	case RunnerTypeKubernetesAgent:
		return true
	case RunnerTypeKubernetesGke:
		return true
	default:
		return false
	}
}

// Defines values for StateStorageType.
const (
	StateStorageTypeKubernetes StateStorageType = "kubernetes"
)

// Valid indicates whether the value is a known member of the StateStorageType enum.
func (e StateStorageType) Valid() bool {
	switch e {
	case StateStorageTypeKubernetes:
		return true
	default:
		return false
	}
}

// Environment An environment.
type Environment struct {
	// CreatedAt The date and time when the resource type was created
	CreatedAt time.Time `json:"created_at"`

	// DisplayName Environment human readable name
	DisplayName string `json:"display_name"`

	// EnvTypeId The environment type for the environment.
	EnvTypeId string `json:"env_type_id"`

	// Id Environment identifier
	Id string `json:"id"`

	// ProjectId Project identifier
	ProjectId string `json:"project_id"`

	// RunnerId The id of the runner to be used to deploy this environment.
	RunnerId string `json:"runner_id"`

	// Status The status of the environment. Environments are normally active unless they have been deleted. A delete_failed status indicates that the destroy failed and a delete can be re-issued.
	Status EnvironmentStatus `json:"status"`

	// StatusMessage An optional message associated with the status.
	StatusMessage *string `json:"status_message,omitempty"`

	// UpdatedAt The date and time when the environment was updated.
	UpdatedAt time.Time `json:"updated_at"`

	// Uuid Unique uid for the environment to identify a unique lifecycle
	Uuid openapi_types.UUID `json:"uuid"`
}

// EnvironmentCreateBody A request to create a new environment.
type EnvironmentCreateBody struct {
	// DisplayName Environment human readable name. The id is used if this is not specified.
	DisplayName *string `json:"display_name,omitempty"`

	// EnvTypeId The environment type for the new environment. This environment type must exist in the org.
	EnvTypeId string `json:"env_type_id"`

	// Id Environment identifier
	Id string `json:"id"`
}

// EnvironmentStatus The status of the environment. Environments are normally active unless they have been deleted. A delete_failed status indicates that the destroy failed and a delete can be re-issued.
type EnvironmentStatus string

// EnvironmentType Summary of an environment type in the org.
type EnvironmentType = EnvironmentTypeSummary

// EnvironmentTypeCreateBody A request to create a new environment type in the org.
type EnvironmentTypeCreateBody struct {
	// DisplayName Human readable name for the environment type. This will be generated if not provided.
	DisplayName *string `json:"display_name,omitempty"`

	// Id Environment type identifier
	Id string `json:"id"`
}

// EnvironmentTypeSummary Summary of an environment type in the org.
type EnvironmentTypeSummary struct {
	// CreatedAt The date and time when the environment type was created
	CreatedAt time.Time `json:"created_at"`

	// DisplayName Human readable name for the environment type
	DisplayName string `json:"display_name"`

	// Id The unique id of the environment type in this org.
	Id string `json:"id"`

	// Uuid Unique uid for the environment type to identify a unique lifecycle
	Uuid openapi_types.UUID `json:"uuid"`
}

// Error A standard error response
type Error struct {
	// Details An optional payload of metadata associated with the error.
	Details *map[string]interface{} `json:"details,omitempty"`

	// Error A short code representing the class of error. This code can be used for tracking and observability or to
	// find appropriate troubleshooting documentation.
	Error string `json:"error"`

	// Message A human-readable explanation of the error.
	Message string `json:"message"`
}

// InternalOrganizationCreateBody A request to create a new organization state in the control plane.
type InternalOrganizationCreateBody struct {
	// Id The unique identifier of the org
	Id string `json:"id"`
}

// K8sAgentRunnerConfiguration Runner configuration for a Kubernetes Agent.
type K8sAgentRunnerConfiguration struct {
	// Job Properties of the Kubernetes Runner Job.
	Job K8sRunnerJobConfig `json:"job"`

	// Key A public ed25519 key in PEM format. The caller must hold the matching private key.
	Key K8sAgentRunnerKey `json:"key"`

	// Type The Runner type.
	Type RunnerType `json:"type"`
}

// K8sAgentRunnerKey A public ed25519 key in PEM format. The caller must hold the matching private key.
type K8sAgentRunnerKey = string

// K8sGkeRunnerConfiguration Runner configuration for a GKE cluster.
type K8sGkeRunnerConfiguration struct {
	// Cluster Configuration to access a GKE cluster.
	Cluster K8sRunnerGkeCluster `json:"cluster"`

	// Job Properties of the Kubernetes Runner Job.
	Job K8sRunnerJobConfig `json:"job"`

	// Type The Runner type.
	Type RunnerType `json:"type"`
}

// K8sRunnerConfiguration Runner configuration for a Kubernetes cluster.
type K8sRunnerConfiguration struct {
	// Cluster Configuration to obtain access token to a generic K8s cluster with auth
	Cluster K8sRunnerK8sCluster `json:"cluster"`

	// Job Properties of the Kubernetes Runner Job.
	Job K8sRunnerJobConfig `json:"job"`

	// Type The Runner type.
	Type RunnerType `json:"type"`
}

// K8sRunnerGcpTemporaryAuth Configuration to obtain temporary access token to access a GKE cluster.
type K8sRunnerGcpTemporaryAuth struct {
	// GcpAudience The URL of the workload identity pool provider used as an audience for OIDC token.
	GcpAudience string `json:"gcp_audience"`

	// GcpServiceAccount The Google service account to impersonate.
	GcpServiceAccount string `json:"gcp_service_account"`
}

// K8sRunnerGkeCluster Configuration to access a GKE cluster.
type K8sRunnerGkeCluster struct {
	// Auth Configuration to obtain temporary access token to access a GKE cluster.
	Auth K8sRunnerGcpTemporaryAuth `json:"auth"`

	// InternalIp Uses the private endpoint address of the cluster if the private endpoint is enabled.
	InternalIp *bool `json:"internal_ip,omitempty"`

	// Location GCP cluster Location.
	Location string `json:"location"`

	// Name Name of the cluster.
	Name      string `json:"name"`
	ProjectId string `json:"project_id"`

	// ProxyUrl Cluster Proxy URL.
	ProxyUrl *string `json:"proxy_url,omitempty"`
}

// K8sRunnerJobConfig Properties of the Kubernetes Runner Job.
type K8sRunnerJobConfig struct {
	// Namespace Namespace where the Job runs.
	Namespace string `json:"namespace"`

	// PodTemplate The Pod Template Spec manifest which defines the runner job pod in the target cluster. It will be merged with the default Job Pod Template Spec.
	PodTemplate *map[string]interface{} `json:"pod_template,omitempty"`

	// ServiceAccount Service Account the Job runs with.
	ServiceAccount string `json:"service_account"`
}

// K8sRunnerK8sCluster Configuration to obtain access token to a generic K8s cluster with auth
type K8sRunnerK8sCluster struct {
	// Auth Configuration to obtain access to a k8s cluster.
	Auth K8sRunnerK8sClusterAuth `json:"auth"`

	// ClusterData Cluster data to access Kubernetes cluster.
	ClusterData K8sRunnerK8sClusterClusterData `json:"cluster_data"`
}

// K8sRunnerK8sClusterAuth Configuration to obtain access to a k8s cluster.
type K8sRunnerK8sClusterAuth struct {
	// ClientCertificateData Kubeconfig Field: user.client-certificate-data
	ClientCertificateData *string `json:"client_certificate_data,omitempty"`

	// ClientKeyData Kubeconfig Field: user.client-key-data
	ClientKeyData *string `json:"client_key_data,omitempty"`

	// ServiceAccountToken Service account token.
	ServiceAccountToken *string `json:"service_account_token,omitempty"`
}

// K8sRunnerK8sClusterClusterData Cluster data to access Kubernetes cluster.
type K8sRunnerK8sClusterClusterData struct {
	// CertificateAuthorityData Kubeconfig Field: cluster.certificate-authority-data
	CertificateAuthorityData string `json:"certificate_authority_data"`

	// ProxyUrl Kubeconfig Field: cluster.proxy-url
	ProxyUrl *string `json:"proxy_url,omitempty"`

	// Server Kubeconfig Field: cluster.server
	Server string `json:"server"`
}

// K8sStorageConfiguration Configuration to use the Kubernetes Backend as backend of this runner. The in-cluster mode is used.
type K8sStorageConfiguration struct {
	// Namespace Where the secrets with the state should be created.
	Namespace string `json:"namespace"`

	// Type Type of the Terraform Backend used by the runner.
	Type StateStorageType `json:"type"`
}

// Module defines model for Module.
type Module struct {
	// Coprovisioned A set of resources to provision after or in parallel with the resource of the current module.
	Coprovisioned []ModuleCoProvisionManifest `json:"coprovisioned"`

	// CreatedAt The date and time when the module was created.
	CreatedAt time.Time `json:"created_at"`

	// Dependencies A mapping of alias to resource dependencies that must be provisioned with this module
	Dependencies map[string]ModuleDependencyManifest `json:"dependencies"`

	// Description An optional text description for this module
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for a module
	Id ModuleId `json:"id"`

	// ModuleInputs The inputs to the module. These may contain expressions referencing the modules context.
	ModuleInputs map[string]interface{} `json:"module_inputs"`

	// ModuleSource The source of the OpenTofu module backing this module.
	ModuleSource *string `json:"module_source,omitempty"`

	// ModuleSourceCode The source code of the OpenTofu module backing this module.
	ModuleSourceCode *string `json:"module_source_code,omitempty"`

	// OrgId The Organization ID
	OrgId string `json:"org_id"`

	// ProviderMapping A mapping of module providers to use when provisioning using this module
	ProviderMapping map[string]string `json:"provider_mapping"`

	// ResourceType The resource type that this module provisions.
	ResourceType string `json:"resource_type"`

	// UpdatedAt The date and time when the module was updated to this version.
	UpdatedAt time.Time `json:"updated_at"`

	// VersionId A unique identifier for this version of the module
	VersionId string `json:"version_id"`
}

// ModuleCoProvisionManifest A resource to provision after or in parallel with the resource of the current module.
type ModuleCoProvisionManifest struct {
	// Class A resource class requested by the resource graph. 'default' is the default value.
	Class *ResourceClass `json:"class,omitempty"`

	// CopyDependentsFromCurrent If true, all resources that depend on the current resource will also depend on (be provisioned after) this coprovisioned resource.
	CopyDependentsFromCurrent bool `json:"copy_dependents_from_current,omitempty"`

	// Id A specific resource id requested by the resource graph
	Id *ResourceId `json:"id,omitempty"`

	// IsDependentOnCurrent If true, this coprovisioned resource will have a dependency on the current resource so that the current
	// resource must be successfully provisioned before the coprovisioned one is.
	IsDependentOnCurrent bool `json:"is_dependent_on_current,omitempty"`

	// Params The parameters to pass for provisioning.
	Params map[string]interface{} `json:"params,omitempty"`

	// Type The resource type to provision
	Type string `json:"type"`
}

// ModuleCreateBody A request to create a new module
type ModuleCreateBody struct {
	// Coprovisioned A set of resources to provision after or in parallel with the resource of the current module.
	Coprovisioned []ModuleCoProvisionManifest `json:"coprovisioned,omitempty"`

	// Dependencies A mapping of alias to resource dependencies that must be provisioned with this module
	Dependencies map[string]ModuleDependencyManifest `json:"dependencies,omitempty"`

	// Description An optional text description for this module
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for a module
	Id ModuleId `json:"id"`

	// ModuleInputs The inputs to the module. These may contain expressions referencing the modules context.
	ModuleInputs map[string]interface{} `json:"module_inputs,omitempty"`

	// ModuleSource The source of the OpenTofu module backing this module. Required, if module source code is not defined.
	ModuleSource *string `json:"module_source,omitempty"`

	// ModuleSourceCode The source code of the OpenTofu module backing this module. Required, if module source is not defined.
	ModuleSourceCode *string `json:"module_source_code,omitempty"`

	// ProviderMapping A mapping of module providers to use when provisioning using this module.
	ProviderMapping map[string]string `json:"provider_mapping,omitempty"`

	// ResourceType The resource type that this module provisions.
	ResourceType string `json:"resource_type"`
}

// ModuleDependencyManifest A dependency to provision before the current resource is provisioned
type ModuleDependencyManifest struct {
	// Class A resource class requested by the resource graph. 'default' is the default value.
	Class *ResourceClass `json:"class,omitempty"`

	// Id A specific resource id requested by the resource graph
	Id *ResourceId `json:"id,omitempty"`

	// Params The parameters to pass to the dependency for provisioning.
	Params map[string]interface{} `json:"params,omitempty"`

	// Type The resource type to provision
	Type string `json:"type"`
}

// ModuleId The unique identifier for a module
type ModuleId = string

// ModuleProvider defines model for ModuleProvider.
type ModuleProvider struct {
	// Configuration Any required configuration for this provider when used.
	Configuration map[string]interface{} `json:"configuration"`

	// CreatedAt The date and time when the provider was created.
	CreatedAt time.Time `json:"created_at"`

	// Description An optional text description for this module provider
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for this module provider under the given provider type
	Id string `json:"id"`

	// OrgId The Organization ID
	OrgId string `json:"org_id"`

	// ProviderType The OpenTofu provider name
	ProviderType string `json:"provider_type"`

	// Source The OpenTofu provider source as a registry coordinate
	Source string `json:"source"`

	// VersionConstraint Specify a specific version of the provider
	VersionConstraint string `json:"version_constraint"`
}

// ModuleProviderCreateBody A request to create a new module provider.
type ModuleProviderCreateBody struct {
	// Configuration Any required configuration for this provider when used.
	Configuration map[string]interface{} `json:"configuration,omitempty"`

	// Description An optional text description for this module provider
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for this module provider under the given provider type
	Id string `json:"id"`

	// ProviderType The OpenTofu provider name
	ProviderType string `json:"provider_type"`

	// Source The OpenTofu provider source as a registry coordinate
	Source string `json:"source"`

	// VersionConstraint Specify a specific version of the provider
	VersionConstraint string `json:"version_constraint"`
}

// ModuleProviderSummary A summary of configuration for an OpenTofu provider that will be used in modules
type ModuleProviderSummary struct {
	// CreatedAt The date and time when the provider was created.
	CreatedAt time.Time `json:"created_at"`

	// Description An optional text description for this module provider
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for this module provider under the given provider type
	Id string `json:"id"`

	// OrgId The Organization ID
	OrgId string `json:"org_id"`

	// ProviderType The OpenTofu provider name
	ProviderType string `json:"provider_type"`

	// Source The OpenTofu provider source as a registry coordinate
	Source string `json:"source"`
}

// ModuleSummary A summary of the module that maps an OpenTofu module to a resource type. The full details can be retrieved through the Get api.
type ModuleSummary struct {
	// CreatedAt The date and time when the module was created.
	CreatedAt time.Time `json:"created_at"`

	// Description An optional text description for this module
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for a module
	Id ModuleId `json:"id"`

	// ModuleSource The source of the OpenTofu module backing this module.
	ModuleSource *string `json:"module_source,omitempty"`

	// ModuleSourceCode The source code of the OpenTofu module backing this module.
	ModuleSourceCode *string `json:"module_source_code,omitempty"`

	// OrgId The Organization ID
	OrgId string `json:"org_id"`

	// ProviderMapping A mapping of module providers to use when provisioning using this module
	ProviderMapping map[string]string `json:"provider_mapping"`

	// ResourceType The resource type that this module provisions.
	ResourceType string `json:"resource_type"`

	// UpdatedAt The date and time when the module was updated to this version.
	UpdatedAt time.Time `json:"updated_at"`

	// VersionId A unique identifier for this version of the module
	VersionId string `json:"version_id"`
}

// Organization The internal state of an organization known by the control plane.
type Organization struct {
	// CreatedAt The date and time when the org state was created.
	CreatedAt time.Time `json:"created_at"`

	// Id The unique identifier of the org
	Id string `json:"id"`

	// Source The source of the org state. This is used to identify the source of the org state, such as a git repository.
	Source OrganizationSource `json:"source"`

	// Uuid Unique uid for the org to identify a unique lifecycle
	Uuid openapi_types.UUID `json:"uuid"`
}

// OrganizationSource The source of the org state. This is used to identify the source of the org state, such as a git repository.
type OrganizationSource string

// Project A project.
type Project struct {
	// CreatedAt The date and time when the project was created
	CreatedAt time.Time `json:"created_at"`

	// DisplayName Project human readable name
	DisplayName string `json:"display_name"`

	// Id Project identifier
	Id string `json:"id"`

	// Status The status of the project. Projects are normally active unless they have been deleted. A deleting project is waiting for it's environments to be deleted.
	Status ProjectStatus `json:"status"`

	// UpdatedAt The date and time when the project was updated due to internal or external changes
	UpdatedAt time.Time `json:"updated_at"`

	// Uuid Unique uid for the project to identify a unique lifecycle
	Uuid openapi_types.UUID `json:"uuid"`
}

// ProjectStatus The status of the project. Projects are normally active unless they have been deleted. A deleting project is waiting for it's environments to be deleted.
type ProjectStatus string

// ProjectCreateBody A request to create a new project.
type ProjectCreateBody struct {
	// DisplayName Project human readable name. The id is used if this is not specified.
	DisplayName *string `json:"display_name,omitempty"`

	// Id Project identifier
	Id string `json:"id"`
}

// ResourceClass A resource class requested by the resource graph. 'default' is the default value.
type ResourceClass = string

// ResourceId A specific resource id requested by the resource graph
type ResourceId = string

// ResourceType A resource type that can be used in modules.
type ResourceType struct {
	// BuiltIn Indicates if this is a built-in resource type
	BuiltIn bool `json:"built_in"`

	// CreatedAt The date and time when the resource type was created
	CreatedAt time.Time `json:"created_at"`

	// Description Resource type description
	Description *string `json:"description,omitempty"`

	// Id Resource type identifier
	Id string `json:"id"`

	// IsDeveloperAccessible Indicates if this resource type is for developers to use in the manifest. Resource types with this flag set to false will not be available as types of resources in a manifest.
	IsDeveloperAccessible bool `json:"is_developer_accessible"`

	// OutputSchema Schema for output parameters
	OutputSchema map[string]interface{} `json:"output_schema"`
}

// ResourceTypeCreateBody A request to create a new resource type.
type ResourceTypeCreateBody struct {
	// Description Resource type description
	Description *string `json:"description,omitempty"`

	// Id Resource type identifier
	Id string `json:"id"`

	// IsDeveloperAccessible Indicates if this resource type is for developers to use in the manifest. Resource types with this flag set to false, will not be available as types of resources in a manifest. If omitted, this property defaults to true.
	IsDeveloperAccessible *bool `json:"is_developer_accessible,omitempty"`

	// OutputSchema Schema for output parameters
	OutputSchema map[string]interface{} `json:"output_schema"`
}

// Rule A summary of a rule that matches resource requests against a module
type Rule = RuleSummary

// RuleCreateBody The properties required to create a new rule that matches modules
type RuleCreateBody struct {
	// EnvId Environment identifier to match this rule. This environment must exist in the app given by project_id.
	// Requires project_id to be set, mutually exclusive with env_type_id.
	EnvId *string `json:"env_id,omitempty"`

	// EnvTypeId The environment type to match this rule. This environment type must exist in the org.
	// Mutually exclusive with env_id.
	EnvTypeId *string `json:"env_type_id,omitempty"`

	// ModuleId The unique identifier for a module
	ModuleId ModuleId `json:"module_id"`

	// ProjectId Project identifier to match this rule. This app must exist in the org.
	ProjectId *string `json:"project_id,omitempty"`

	// ResourceClass A resource class requested by the resource graph. 'default' is the default value.
	ResourceClass *ResourceClass `json:"resource_class,omitempty"`

	// ResourceId A specific resource id requested by the resource graph
	ResourceId *ResourceId `json:"resource_id,omitempty"`
}

// RuleSummary A summary of a rule that matches resource requests against a module
type RuleSummary struct {
	// CreatedAt The time this rule was created
	CreatedAt time.Time `json:"created_at"`

	// EnvId The optional environment id that this rule matches.
	EnvId *string `json:"env_id,omitempty"`

	// EnvTypeId The optional env type id that this rule matches.
	EnvTypeId *string `json:"env_type_id,omitempty"`

	// Id The unique identifier for the rule under the organization.
	Id openapi_types.UUID `json:"id"`

	// ModuleId The unique identifier for a module
	ModuleId ModuleId `json:"module_id"`

	// OrgId The Organization ID.
	OrgId string `json:"org_id"`

	// ProjectId The optional project id that this rule matches.
	ProjectId *string `json:"project_id,omitempty"`

	// ResourceClass The resource class to match
	ResourceClass string `json:"resource_class"`

	// ResourceId The resource id to match
	ResourceId *string `json:"resource_id,omitempty"`

	// ResourceType The resource type matched by this rule
	ResourceType string `json:"resource_type"`
}

// Runner defines model for Runner.
type Runner struct {
	// CreatedAt The date and time when the runner was created.
	CreatedAt time.Time `json:"created_at"`

	// Description An optional text description for this runner.
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for the runner under the organization.
	Id string `json:"id"`

	// OrgId The Organization ID.
	OrgId string `json:"org_id"`

	// RunnerConfiguration The data needed to configure the runner.
	RunnerConfiguration RunnerConfiguration `json:"runner_configuration"`

	// StateStorageConfiguration Configuration for the Terraform Backend used by the runner.
	StateStorageConfiguration StateStorageConfiguration `json:"state_storage_configuration"`

	// UpdatedAt The date and time when the runner was updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// RunnerConfiguration The data needed to configure the runner.
type RunnerConfiguration struct {
	union json.RawMessage
}

// RunnerConfigurationSummary A summary of the runner configuration.
type RunnerConfigurationSummary struct {
	// Type The Runner type.
	Type RunnerType `json:"type"`
}

// RunnerCreateBody A request to create a new runner.
type RunnerCreateBody struct {
	// Description An optional text description for this runner.
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for the runner under the organization.
	Id string `json:"id"`

	// RunnerConfiguration The data needed to configure the runner.
	RunnerConfiguration RunnerConfiguration `json:"runner_configuration"`

	// StateStorageConfiguration Configuration for the Terraform Backend used by the runner.
	StateStorageConfiguration StateStorageConfiguration `json:"state_storage_configuration"`
}

// RunnerRule A summary of a rule that matches resource requests against a module
type RunnerRule = RunnerRuleSummary

// RunnerRuleCreateBody The properties required to create a new rule that matches runners
type RunnerRuleCreateBody struct {
	// EnvTypeId The environment type to match this rule. This environment type must exist in the org.
	EnvTypeId *string `json:"env_type_id,omitempty"`

	// ProjectId Project identifier to match this rule. This project must exist in the org.
	ProjectId *string `json:"project_id,omitempty"`

	// RunnerId The unique identifier for a runner
	RunnerId string `json:"runner_id"`
}

// RunnerRuleSummary A summary of a rule that matches resource requests against a module
type RunnerRuleSummary struct {
	// CreatedAt The time this rule was created
	CreatedAt time.Time `json:"created_at"`

	// EnvTypeId The optional env type id that this rule matches.
	EnvTypeId string `json:"env_type_id"`

	// Id The unique identifier for the rule under the organization.
	Id openapi_types.UUID `json:"id"`

	// OrgId The Organization ID.
	OrgId string `json:"org_id"`

	// ProjectId The optional project id that this rule matches.
	ProjectId string `json:"project_id"`

	// RunnerId The unique identifier for a runner
	RunnerId string `json:"runner_id"`
}

// RunnerSummary A summary of configuration a runner.
type RunnerSummary struct {
	// CreatedAt The date and time when the runner was created.
	CreatedAt time.Time `json:"created_at"`

	// Description An optional text description for this runner.
	Description *string `json:"description,omitempty"`

	// Id The unique identifier for the runner under the organization.
	Id string `json:"id"`

	// OrgId The Organization ID.
	OrgId string `json:"org_id"`

	// RunnerConfiguration A summary of the runner configuration.
	RunnerConfiguration *RunnerConfigurationSummary `json:"runner_configuration,omitempty"`

	// StateStorageConfiguration Summary of the state storage configuration.
	StateStorageConfiguration *StateStorageConfigurationSummary `json:"state_storage_configuration,omitempty"`

	// UpdatedAt The date and time when the runner was updated.
	UpdatedAt time.Time `json:"updated_at"`
}

// RunnerType The Runner type.
type RunnerType string

// StateStorageConfiguration Configuration for the Terraform Backend used by the runner.
type StateStorageConfiguration struct {
	union json.RawMessage
}

// StateStorageConfigurationSummary Summary of the state storage configuration.
type StateStorageConfigurationSummary struct {
	// Type Type of the Terraform Backend used by the runner.
	Type StateStorageType `json:"type"`
}

// StateStorageType Type of the Terraform Backend used by the runner.
type StateStorageType string

// OrgIdPathParam defines model for orgIdPathParam.
type OrgIdPathParam = string

// ProjectIdPathParam defines model for projectIdPathParam.
type ProjectIdPathParam = string

// N400BadRequest A standard error response
type N400BadRequest = Error

// N409Conflict A standard error response
type N409Conflict = Error

// CreateInternalOrganizationJSONRequestBody defines body for CreateInternalOrganization for application/json ContentType.
type CreateInternalOrganizationJSONRequestBody = InternalOrganizationCreateBody

// CreateEnvironmentTypeJSONRequestBody defines body for CreateEnvironmentType for application/json ContentType.
type CreateEnvironmentTypeJSONRequestBody = EnvironmentTypeCreateBody

// CreateModuleProviderJSONRequestBody defines body for CreateModuleProvider for application/json ContentType.
type CreateModuleProviderJSONRequestBody = ModuleProviderCreateBody

// CreateModuleRuleInOrgJSONRequestBody defines body for CreateModuleRuleInOrg for application/json ContentType.
type CreateModuleRuleInOrgJSONRequestBody = RuleCreateBody

// CreateModuleJSONRequestBody defines body for CreateModule for application/json ContentType.
type CreateModuleJSONRequestBody = ModuleCreateBody

// CreateProjectJSONRequestBody defines body for CreateProject for application/json ContentType.
type CreateProjectJSONRequestBody = ProjectCreateBody

// CreateEnvironmentJSONRequestBody defines body for CreateEnvironment for application/json ContentType.
type CreateEnvironmentJSONRequestBody = EnvironmentCreateBody

// CreateResourceTypeJSONRequestBody defines body for CreateResourceType for application/json ContentType.
type CreateResourceTypeJSONRequestBody = ResourceTypeCreateBody

// CreateRunnerRuleInOrgJSONRequestBody defines body for CreateRunnerRuleInOrg for application/json ContentType.
type CreateRunnerRuleInOrgJSONRequestBody = RunnerRuleCreateBody

// CreateRunnerJSONRequestBody defines body for CreateRunner for application/json ContentType.
type CreateRunnerJSONRequestBody = RunnerCreateBody

// AsK8sRunnerConfiguration returns the union data inside the RunnerConfiguration as a K8sRunnerConfiguration
func (t RunnerConfiguration) AsK8sRunnerConfiguration() (K8sRunnerConfiguration, error) {
	var body K8sRunnerConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromK8sRunnerConfiguration overwrites any union data inside the RunnerConfiguration as the provided K8sRunnerConfiguration
func (t *RunnerConfiguration) FromK8sRunnerConfiguration(v K8sRunnerConfiguration) error {
	v.Type = "kubernetes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeK8sRunnerConfiguration performs a merge with any union data inside the RunnerConfiguration, using the provided K8sRunnerConfiguration
func (t *RunnerConfiguration) MergeK8sRunnerConfiguration(v K8sRunnerConfiguration) error {
	v.Type = "kubernetes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsK8sGkeRunnerConfiguration returns the union data inside the RunnerConfiguration as a K8sGkeRunnerConfiguration
func (t RunnerConfiguration) AsK8sGkeRunnerConfiguration() (K8sGkeRunnerConfiguration, error) {
	var body K8sGkeRunnerConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromK8sGkeRunnerConfiguration overwrites any union data inside the RunnerConfiguration as the provided K8sGkeRunnerConfiguration
func (t *RunnerConfiguration) FromK8sGkeRunnerConfiguration(v K8sGkeRunnerConfiguration) error {
	v.Type = "kubernetes-gke"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeK8sGkeRunnerConfiguration performs a merge with any union data inside the RunnerConfiguration, using the provided K8sGkeRunnerConfiguration
func (t *RunnerConfiguration) MergeK8sGkeRunnerConfiguration(v K8sGkeRunnerConfiguration) error {
	v.Type = "kubernetes-gke"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsK8sAgentRunnerConfiguration returns the union data inside the RunnerConfiguration as a K8sAgentRunnerConfiguration
func (t RunnerConfiguration) AsK8sAgentRunnerConfiguration() (K8sAgentRunnerConfiguration, error) {
	var body K8sAgentRunnerConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromK8sAgentRunnerConfiguration overwrites any union data inside the RunnerConfiguration as the provided K8sAgentRunnerConfiguration
func (t *RunnerConfiguration) FromK8sAgentRunnerConfiguration(v K8sAgentRunnerConfiguration) error {
	v.Type = "kubernetes-agent"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeK8sAgentRunnerConfiguration performs a merge with any union data inside the RunnerConfiguration, using the provided K8sAgentRunnerConfiguration
func (t *RunnerConfiguration) MergeK8sAgentRunnerConfiguration(v K8sAgentRunnerConfiguration) error {
	v.Type = "kubernetes-agent"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t RunnerConfiguration) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t RunnerConfiguration) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "kubernetes":
		return t.AsK8sRunnerConfiguration()
	case "kubernetes-agent":
		return t.AsK8sAgentRunnerConfiguration()
	case "kubernetes-gke":
		return t.AsK8sGkeRunnerConfiguration()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t RunnerConfiguration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *RunnerConfiguration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// AsK8sStorageConfiguration returns the union data inside the StateStorageConfiguration as a K8sStorageConfiguration
func (t StateStorageConfiguration) AsK8sStorageConfiguration() (K8sStorageConfiguration, error) {
	var body K8sStorageConfiguration
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromK8sStorageConfiguration overwrites any union data inside the StateStorageConfiguration as the provided K8sStorageConfiguration
func (t *StateStorageConfiguration) FromK8sStorageConfiguration(v K8sStorageConfiguration) error {
	v.Type = "kubernetes"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeK8sStorageConfiguration performs a merge with any union data inside the StateStorageConfiguration, using the provided K8sStorageConfiguration
func (t *StateStorageConfiguration) MergeK8sStorageConfiguration(v K8sStorageConfiguration) error {
	v.Type = "kubernetes"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t StateStorageConfiguration) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t StateStorageConfiguration) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "kubernetes":
		return t.AsK8sStorageConfiguration()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t StateStorageConfiguration) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *StateStorageConfiguration) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateInternalOrganizationWithBody request with any body
	CreateInternalOrganizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateInternalOrganization(ctx context.Context, body CreateInternalOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateEnvironmentTypeWithBody request with any body
	CreateEnvironmentTypeWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateEnvironmentType(ctx context.Context, orgId OrgIdPathParam, body CreateEnvironmentTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateModuleProviderWithBody request with any body
	CreateModuleProviderWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateModuleProvider(ctx context.Context, orgId OrgIdPathParam, body CreateModuleProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateModuleRuleInOrgWithBody request with any body
	CreateModuleRuleInOrgWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateModuleRuleInOrg(ctx context.Context, orgId OrgIdPathParam, body CreateModuleRuleInOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateModuleWithBody request with any body
	CreateModuleWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateModule(ctx context.Context, orgId OrgIdPathParam, body CreateModuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateProjectWithBody request with any body
	CreateProjectWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateProject(ctx context.Context, orgId OrgIdPathParam, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateEnvironmentWithBody request with any body
	CreateEnvironmentWithBody(ctx context.Context, orgId OrgIdPathParam, projectId ProjectIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateEnvironment(ctx context.Context, orgId OrgIdPathParam, projectId ProjectIdPathParam, body CreateEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateResourceTypeWithBody request with any body
	CreateResourceTypeWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateResourceType(ctx context.Context, orgId OrgIdPathParam, body CreateResourceTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRunnerRuleInOrgWithBody request with any body
	CreateRunnerRuleInOrgWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRunnerRuleInOrg(ctx context.Context, orgId OrgIdPathParam, body CreateRunnerRuleInOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateRunnerWithBody request with any body
	CreateRunnerWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateRunner(ctx context.Context, orgId OrgIdPathParam, body CreateRunnerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateInternalOrganizationWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateInternalOrganizationRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateInternalOrganization(ctx context.Context, body CreateInternalOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateInternalOrganizationRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateEnvironmentTypeWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEnvironmentTypeRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateEnvironmentType(ctx context.Context, orgId OrgIdPathParam, body CreateEnvironmentTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEnvironmentTypeRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateModuleProviderWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateModuleProviderRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateModuleProvider(ctx context.Context, orgId OrgIdPathParam, body CreateModuleProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateModuleProviderRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateModuleRuleInOrgWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateModuleRuleInOrgRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateModuleRuleInOrg(ctx context.Context, orgId OrgIdPathParam, body CreateModuleRuleInOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateModuleRuleInOrgRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateModuleWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateModuleRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateModule(ctx context.Context, orgId OrgIdPathParam, body CreateModuleJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateModuleRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProjectWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProjectRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateProject(ctx context.Context, orgId OrgIdPathParam, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateProjectRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateEnvironmentWithBody(ctx context.Context, orgId OrgIdPathParam, projectId ProjectIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEnvironmentRequestWithBody(c.Server, orgId, projectId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateEnvironment(ctx context.Context, orgId OrgIdPathParam, projectId ProjectIdPathParam, body CreateEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateEnvironmentRequest(c.Server, orgId, projectId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateResourceTypeWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateResourceTypeRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateResourceType(ctx context.Context, orgId OrgIdPathParam, body CreateResourceTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateResourceTypeRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRunnerRuleInOrgWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRunnerRuleInOrgRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRunnerRuleInOrg(ctx context.Context, orgId OrgIdPathParam, body CreateRunnerRuleInOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRunnerRuleInOrgRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRunnerWithBody(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRunnerRequestWithBody(c.Server, orgId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateRunner(ctx context.Context, orgId OrgIdPathParam, body CreateRunnerJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateRunnerRequest(c.Server, orgId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateInternalOrganizationRequest calls the generic CreateInternalOrganization builder with application/json body
func NewCreateInternalOrganizationRequest(server string, body CreateInternalOrganizationJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateInternalOrganizationRequestWithBody(server, "application/json", bodyReader)
}

// NewCreateInternalOrganizationRequestWithBody generates requests for CreateInternalOrganization with any type of body
func NewCreateInternalOrganizationRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/internal/orgs")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateEnvironmentTypeRequest calls the generic CreateEnvironmentType builder with application/json body
func NewCreateEnvironmentTypeRequest(server string, orgId OrgIdPathParam, body CreateEnvironmentTypeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateEnvironmentTypeRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewCreateEnvironmentTypeRequestWithBody generates requests for CreateEnvironmentType with any type of body
func NewCreateEnvironmentTypeRequestWithBody(server string, orgId OrgIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/env-types", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateModuleProviderRequest calls the generic CreateModuleProvider builder with application/json body
func NewCreateModuleProviderRequest(server string, orgId OrgIdPathParam, body CreateModuleProviderJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateModuleProviderRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewCreateModuleProviderRequestWithBody generates requests for CreateModuleProvider with any type of body
func NewCreateModuleProviderRequestWithBody(server string, orgId OrgIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/module-providers", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateModuleRuleInOrgRequest calls the generic CreateModuleRuleInOrg builder with application/json body
func NewCreateModuleRuleInOrgRequest(server string, orgId OrgIdPathParam, body CreateModuleRuleInOrgJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateModuleRuleInOrgRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewCreateModuleRuleInOrgRequestWithBody generates requests for CreateModuleRuleInOrg with any type of body
func NewCreateModuleRuleInOrgRequestWithBody(server string, orgId OrgIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/module-rules", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateModuleRequest calls the generic CreateModule builder with application/json body
func NewCreateModuleRequest(server string, orgId OrgIdPathParam, body CreateModuleJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateModuleRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewCreateModuleRequestWithBody generates requests for CreateModule with any type of body
func NewCreateModuleRequestWithBody(server string, orgId OrgIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/modules", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateProjectRequest calls the generic CreateProject builder with application/json body
func NewCreateProjectRequest(server string, orgId OrgIdPathParam, body CreateProjectJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateProjectRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewCreateProjectRequestWithBody generates requests for CreateProject with any type of body
func NewCreateProjectRequestWithBody(server string, orgId OrgIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/projects", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateEnvironmentRequest calls the generic CreateEnvironment builder with application/json body
func NewCreateEnvironmentRequest(server string, orgId OrgIdPathParam, projectId ProjectIdPathParam, body CreateEnvironmentJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateEnvironmentRequestWithBody(server, orgId, projectId, "application/json", bodyReader)
}

// NewCreateEnvironmentRequestWithBody generates requests for CreateEnvironment with any type of body
func NewCreateEnvironmentRequestWithBody(server string, orgId OrgIdPathParam, projectId ProjectIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	var pathParam1 string

	pathParam1, err = runtime.StyleParamWithOptions("simple", false, "projectId", projectId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/projects/%s/envs", pathParam0, pathParam1)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateResourceTypeRequest calls the generic CreateResourceType builder with application/json body
func NewCreateResourceTypeRequest(server string, orgId OrgIdPathParam, body CreateResourceTypeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateResourceTypeRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewCreateResourceTypeRequestWithBody generates requests for CreateResourceType with any type of body
func NewCreateResourceTypeRequestWithBody(server string, orgId OrgIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/resource-types", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateRunnerRuleInOrgRequest calls the generic CreateRunnerRuleInOrg builder with application/json body
func NewCreateRunnerRuleInOrgRequest(server string, orgId OrgIdPathParam, body CreateRunnerRuleInOrgJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRunnerRuleInOrgRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewCreateRunnerRuleInOrgRequestWithBody generates requests for CreateRunnerRuleInOrg with any type of body
func NewCreateRunnerRuleInOrgRequestWithBody(server string, orgId OrgIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/runner-rules", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewCreateRunnerRequest calls the generic CreateRunner builder with application/json body
func NewCreateRunnerRequest(server string, orgId OrgIdPathParam, body CreateRunnerJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateRunnerRequestWithBody(server, orgId, "application/json", bodyReader)
}

// NewCreateRunnerRequestWithBody generates requests for CreateRunner with any type of body
func NewCreateRunnerRequestWithBody(server string, orgId OrgIdPathParam, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "orgId", orgId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/runners", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateInternalOrganizationWithBodyWithResponse request with any body
	CreateInternalOrganizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInternalOrganizationResponse, error)

	CreateInternalOrganizationWithResponse(ctx context.Context, body CreateInternalOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInternalOrganizationResponse, error)

	// CreateEnvironmentTypeWithBodyWithResponse request with any body
	CreateEnvironmentTypeWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEnvironmentTypeResponse, error)

	CreateEnvironmentTypeWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateEnvironmentTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEnvironmentTypeResponse, error)

	// CreateModuleProviderWithBodyWithResponse request with any body
	CreateModuleProviderWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateModuleProviderResponse, error)

	CreateModuleProviderWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateModuleProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateModuleProviderResponse, error)

	// CreateModuleRuleInOrgWithBodyWithResponse request with any body
	CreateModuleRuleInOrgWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateModuleRuleInOrgResponse, error)

	CreateModuleRuleInOrgWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateModuleRuleInOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateModuleRuleInOrgResponse, error)

	// CreateModuleWithBodyWithResponse request with any body
	CreateModuleWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateModuleResponse, error)

	CreateModuleWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateModuleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateModuleResponse, error)

	// CreateProjectWithBodyWithResponse request with any body
	CreateProjectWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProjectResponse, error)

	CreateProjectWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProjectResponse, error)

	// CreateEnvironmentWithBodyWithResponse request with any body
	CreateEnvironmentWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, projectId ProjectIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEnvironmentResponse, error)

	CreateEnvironmentWithResponse(ctx context.Context, orgId OrgIdPathParam, projectId ProjectIdPathParam, body CreateEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEnvironmentResponse, error)

	// CreateResourceTypeWithBodyWithResponse request with any body
	CreateResourceTypeWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateResourceTypeResponse, error)

	CreateResourceTypeWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateResourceTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateResourceTypeResponse, error)

	// CreateRunnerRuleInOrgWithBodyWithResponse request with any body
	CreateRunnerRuleInOrgWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRunnerRuleInOrgResponse, error)

	CreateRunnerRuleInOrgWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateRunnerRuleInOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRunnerRuleInOrgResponse, error)

	// CreateRunnerWithBodyWithResponse request with any body
	CreateRunnerWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRunnerResponse, error)

	CreateRunnerWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateRunnerJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRunnerResponse, error)
}

type CreateInternalOrganizationResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Organization
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateInternalOrganizationResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateInternalOrganizationResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateEnvironmentTypeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *EnvironmentType
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateEnvironmentTypeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateEnvironmentTypeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateModuleProviderResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ModuleProvider
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateModuleProviderResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateModuleProviderResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateModuleRuleInOrgResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Rule
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateModuleRuleInOrgResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateModuleRuleInOrgResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateModuleResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Module
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateModuleResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateModuleResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateProjectResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Project
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateProjectResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateProjectResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateEnvironmentResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Environment
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateEnvironmentResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateEnvironmentResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateResourceTypeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *ResourceType
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateResourceTypeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateResourceTypeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateRunnerRuleInOrgResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *RunnerRule
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateRunnerRuleInOrgResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRunnerRuleInOrgResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type CreateRunnerResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON201      *Runner
	JSON400      *N400BadRequest
	JSON409      *N409Conflict
}

// Status returns HTTPResponse.Status
func (r CreateRunnerResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateRunnerResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateInternalOrganizationWithBodyWithResponse request with arbitrary body returning *CreateInternalOrganizationResponse
func (c *ClientWithResponses) CreateInternalOrganizationWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateInternalOrganizationResponse, error) {
	rsp, err := c.CreateInternalOrganizationWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateInternalOrganizationResponse(rsp)
}

func (c *ClientWithResponses) CreateInternalOrganizationWithResponse(ctx context.Context, body CreateInternalOrganizationJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateInternalOrganizationResponse, error) {
	rsp, err := c.CreateInternalOrganization(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateInternalOrganizationResponse(rsp)
}

// CreateEnvironmentTypeWithBodyWithResponse request with arbitrary body returning *CreateEnvironmentTypeResponse
func (c *ClientWithResponses) CreateEnvironmentTypeWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEnvironmentTypeResponse, error) {
	rsp, err := c.CreateEnvironmentTypeWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEnvironmentTypeResponse(rsp)
}

func (c *ClientWithResponses) CreateEnvironmentTypeWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateEnvironmentTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEnvironmentTypeResponse, error) {
	rsp, err := c.CreateEnvironmentType(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEnvironmentTypeResponse(rsp)
}

// CreateModuleProviderWithBodyWithResponse request with arbitrary body returning *CreateModuleProviderResponse
func (c *ClientWithResponses) CreateModuleProviderWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateModuleProviderResponse, error) {
	rsp, err := c.CreateModuleProviderWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateModuleProviderResponse(rsp)
}

func (c *ClientWithResponses) CreateModuleProviderWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateModuleProviderJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateModuleProviderResponse, error) {
	rsp, err := c.CreateModuleProvider(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateModuleProviderResponse(rsp)
}

// CreateModuleRuleInOrgWithBodyWithResponse request with arbitrary body returning *CreateModuleRuleInOrgResponse
func (c *ClientWithResponses) CreateModuleRuleInOrgWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateModuleRuleInOrgResponse, error) {
	rsp, err := c.CreateModuleRuleInOrgWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateModuleRuleInOrgResponse(rsp)
}

func (c *ClientWithResponses) CreateModuleRuleInOrgWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateModuleRuleInOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateModuleRuleInOrgResponse, error) {
	rsp, err := c.CreateModuleRuleInOrg(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateModuleRuleInOrgResponse(rsp)
}

// CreateModuleWithBodyWithResponse request with arbitrary body returning *CreateModuleResponse
func (c *ClientWithResponses) CreateModuleWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateModuleResponse, error) {
	rsp, err := c.CreateModuleWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateModuleResponse(rsp)
}

func (c *ClientWithResponses) CreateModuleWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateModuleJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateModuleResponse, error) {
	rsp, err := c.CreateModule(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateModuleResponse(rsp)
}

// CreateProjectWithBodyWithResponse request with arbitrary body returning *CreateProjectResponse
func (c *ClientWithResponses) CreateProjectWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateProjectResponse, error) {
	rsp, err := c.CreateProjectWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProjectResponse(rsp)
}

func (c *ClientWithResponses) CreateProjectWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateProjectJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateProjectResponse, error) {
	rsp, err := c.CreateProject(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateProjectResponse(rsp)
}

// CreateEnvironmentWithBodyWithResponse request with arbitrary body returning *CreateEnvironmentResponse
func (c *ClientWithResponses) CreateEnvironmentWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, projectId ProjectIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateEnvironmentResponse, error) {
	rsp, err := c.CreateEnvironmentWithBody(ctx, orgId, projectId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEnvironmentResponse(rsp)
}

func (c *ClientWithResponses) CreateEnvironmentWithResponse(ctx context.Context, orgId OrgIdPathParam, projectId ProjectIdPathParam, body CreateEnvironmentJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateEnvironmentResponse, error) {
	rsp, err := c.CreateEnvironment(ctx, orgId, projectId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateEnvironmentResponse(rsp)
}

// CreateResourceTypeWithBodyWithResponse request with arbitrary body returning *CreateResourceTypeResponse
func (c *ClientWithResponses) CreateResourceTypeWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateResourceTypeResponse, error) {
	rsp, err := c.CreateResourceTypeWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateResourceTypeResponse(rsp)
}

func (c *ClientWithResponses) CreateResourceTypeWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateResourceTypeJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateResourceTypeResponse, error) {
	rsp, err := c.CreateResourceType(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateResourceTypeResponse(rsp)
}

// CreateRunnerRuleInOrgWithBodyWithResponse request with arbitrary body returning *CreateRunnerRuleInOrgResponse
func (c *ClientWithResponses) CreateRunnerRuleInOrgWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRunnerRuleInOrgResponse, error) {
	rsp, err := c.CreateRunnerRuleInOrgWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRunnerRuleInOrgResponse(rsp)
}

func (c *ClientWithResponses) CreateRunnerRuleInOrgWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateRunnerRuleInOrgJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRunnerRuleInOrgResponse, error) {
	rsp, err := c.CreateRunnerRuleInOrg(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRunnerRuleInOrgResponse(rsp)
}

// CreateRunnerWithBodyWithResponse request with arbitrary body returning *CreateRunnerResponse
func (c *ClientWithResponses) CreateRunnerWithBodyWithResponse(ctx context.Context, orgId OrgIdPathParam, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateRunnerResponse, error) {
	rsp, err := c.CreateRunnerWithBody(ctx, orgId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRunnerResponse(rsp)
}

func (c *ClientWithResponses) CreateRunnerWithResponse(ctx context.Context, orgId OrgIdPathParam, body CreateRunnerJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateRunnerResponse, error) {
	rsp, err := c.CreateRunner(ctx, orgId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateRunnerResponse(rsp)
}

// ParseCreateInternalOrganizationResponse parses an HTTP response from a CreateInternalOrganizationWithResponse call
func ParseCreateInternalOrganizationResponse(rsp *http.Response) (*CreateInternalOrganizationResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateInternalOrganizationResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Organization
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateEnvironmentTypeResponse parses an HTTP response from a CreateEnvironmentTypeWithResponse call
func ParseCreateEnvironmentTypeResponse(rsp *http.Response) (*CreateEnvironmentTypeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateEnvironmentTypeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest EnvironmentType
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateModuleProviderResponse parses an HTTP response from a CreateModuleProviderWithResponse call
func ParseCreateModuleProviderResponse(rsp *http.Response) (*CreateModuleProviderResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateModuleProviderResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ModuleProvider
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateModuleRuleInOrgResponse parses an HTTP response from a CreateModuleRuleInOrgWithResponse call
func ParseCreateModuleRuleInOrgResponse(rsp *http.Response) (*CreateModuleRuleInOrgResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateModuleRuleInOrgResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Rule
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateModuleResponse parses an HTTP response from a CreateModuleWithResponse call
func ParseCreateModuleResponse(rsp *http.Response) (*CreateModuleResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateModuleResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Module
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateProjectResponse parses an HTTP response from a CreateProjectWithResponse call
func ParseCreateProjectResponse(rsp *http.Response) (*CreateProjectResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateProjectResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Project
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateEnvironmentResponse parses an HTTP response from a CreateEnvironmentWithResponse call
func ParseCreateEnvironmentResponse(rsp *http.Response) (*CreateEnvironmentResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateEnvironmentResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Environment
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateResourceTypeResponse parses an HTTP response from a CreateResourceTypeWithResponse call
func ParseCreateResourceTypeResponse(rsp *http.Response) (*CreateResourceTypeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateResourceTypeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest ResourceType
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateRunnerRuleInOrgResponse parses an HTTP response from a CreateRunnerRuleInOrgWithResponse call
func ParseCreateRunnerRuleInOrgResponse(rsp *http.Response) (*CreateRunnerRuleInOrgResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRunnerRuleInOrgResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest RunnerRule
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}

// ParseCreateRunnerResponse parses an HTTP response from a CreateRunnerWithResponse call
func ParseCreateRunnerResponse(rsp *http.Response) (*CreateRunnerResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateRunnerResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 201:
		var dest Runner
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON201 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400BadRequest
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409Conflict
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON409 = &dest

	}

	return response, nil
}
